---
- name: check docker status 
  hosts: web
  tasks: 
  
  - name: check_docker 
    ansible.buildin.shell:
        cmd: systemctl status docker 
    register: result 


  - name: Display result 
    debug:
      msg:"{{result.stdout_lines}}"
      