---
- hosts: web 
  become: yes
  become_method: sudo
  tasks: 

  - name: Install docker 
    yum:
     name: docker 
     state: latest 
     update_cache: yes


  - name: start docker 
    service: 
      name: docker 
      state: started 
      