---
- hosts: web
  become: yes
  become_method: sudo
  tasks:

  - name: stop docker 
    service:
       name: docker
       state: stopped

  - name: uninstall docker 
    yum: 
     name: docker
     state: absent
     

    