--- 
- hosts: web 
  become: yes
  becom_method: yes
  tasks: 

  - name: Install docker 
    yum: 
     name: docker 
     state: latest
     update_cache: yes
  when: ansible_facts['os_family'] == "RHEL"


  - name: start docker 
    service:
      name: docker 
      state: started
  when: ansible_facts['os_family'] == "RHEL"


